### ISSUE TITLE
Errors during setup aren't failing the action

### ISSUE THREAD

**Issue by timbussmann** [Particular/setup-ravendb-action#9]
Some failures of the setup action are not failing the action itself and will cause further problems down the line when test projects are run. E.g. the following error in the setup-action was swallowed:

> Invoke-WebRequest: D:\a\_actions\Particular\setup-ravendb-action\v1.0.0\setup.ps1:158
> ***"Url":"/admin/cluster/node?url=http%3a%2f%2f***%3a8080&tag=B&watcher=***&assignedCores=1","Type":"System.InvalidOperationException","Message":"An exception was thrown while trying to connect to 'http://***:8080':\nSystem.TimeoutException: Waited for 00:00:15 to receive TCP information from 'http://***:8080' and got no response\n   at Raven.Server.ServerWide.ServerStore.TestConnectionToRemote(String url, String database) in C:\\Builds\\RavenDB-Stable-5.3\\53040\\src\\Raven.Server\\ServerWide\\ServerStore.cs:line 3262","Error":"System.InvalidOperationException: An exception was thrown while trying to connect to 'http://***:8080':\nSystem.TimeoutException: Waited for 00:00:15 to receive TCP information from 'http://***:8080' and got no response\n   at Raven.Server.ServerWide.ServerStore.TestConnectionToRemote(String url, String database) in C:\\Builds\\RavenDB-Stable-5.3\\53040\\src\\Raven.Server\\ServerWide\\ServerStore.cs:line 3262\n   at Raven.Server.Documents.Handlers.Admin.RachisAdminHandler.AddNode() in C:\\Builds\\RavenDB-Stable-5.3\\53040\\src\\Raven.Server\\Documents\\Handlers\\Admin\\RachisAdminHandler.cs:line 318\n   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\\Builds\\RavenDB-Stable-5.3\\53040\\src\\Raven.Server\\Routing\\RequestRouter.cs:line 358\n   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\\Builds\\RavenDB-Stable-5.3\\53040\\src\\Raven.Server\\RavenServerStartup.cs:line 176"***

This causes tests to fail with error messages like

> Raven.Client.Exceptions.RavenException : System.ArgumentException: Failed to add node B, because we don't have it in the cluster.

**Comment by danielmarbach** [comment]
Also related to https://github.com/Particular/setup-ravendb-action/issues/4

**Comment by helenktsai** [comment]
Should be addressed by #20, #25, and #31. The latter points to #30 to capture any further issues if anything unexpected pops up.
